name: Composer Conflicts Section Upgrade

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * 1' # At 03:00 AM on Monday

jobs:
  upgrade-conflicts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install --no-dev

      - name: Run upgrade script
        env:
          BOT_PERSONAL_ACCESS_TOKEN: ${{ secrets.BOT_PERSONAL_ACCESS_TOKEN }}
          FORK_REPO_OWNER: ${{ vars.FORK_REPO_OWNER }}
          FORK_REPO_NAME: ${{ vars.FORK_REPO_NAME }}
          REPO_OWNER: ${{ vars.REPO_OWNER }}
          REPO_NAME: ${{ vars.REPO_NAME }}
          API_PAUSE_BETWEEN_ACTIONS_SECONDS: ${{ vars.API_PAUSE_BETWEEN_ACTIONS_SECONDS }}
          IS_ENABLED: ${{ vars.IS_ENABLED }}
          WORDFENCE_API_KEY: ${{ vars.WORDFENCE_API_KEY }}
          WORDFENCE_SCANNER_FEED_URL: ${{ vars.WORDFENCE_SCANNER_FEED_URL }}
          WORDFENCE_PRODUCTION_FEED_URL: ${{ vars.WORDFENCE_PRODUCTION_FEED_URL }}
        run: php composer_conflict_upgrade.php
